#!/usr/bin/env bash

set -ev

cp ./scripts/pantheon/pantheon.yml deploy
cd deploy
cd vendor/bin && ln -s ../drush/drush/drush drush9 && cd ../..
mkdir web/private
cp -r vendor/evolvingweb/drupal-ci/pantheon/quicksilver web/private/scripts

set +v
